### ISSUE TITLE
Add .vsix to branch for Coder or Theia Browser Code Editors

### ISSUE THREAD

**Issue by herberthobregon** [runem/lit-analyzer#104]
# vscode-lit-plugin

Editors in the browser is the next thing to come, like Github Codespaces and there are IDEs like `Coder` or `Theia` that support VScode extensions, and its way to install is very simple if you already have the `.vsix` in the repo. Currently, I have to clone the repo and generate that file. It would be very useful if you add it in the code releases or inside the package root

> REF
> https://theia-ide.org/docs/composing_applications/

**Comment by runem** [comment]
I think this is a great idea :blush: I actually already build the `.vsix` as a part of running Github Actions (see the artifact here: https://github.com/runem/lit-analyzer/actions/runs/101599186), so it should be available for every commit of `lit-analyzer`. However, I think it would be a good idea to have a more "official" `.vsix` file for each published version. I'm a bit hesitant to commit it as a part of the repo, but I would rather include it as a binary for each release: https://github.com/runem/lit-analyzer/releases :+1:
