### ISSUE TITLE
Feature request: decorate messages in vscode-lit-plugin with plugin name

### ISSUE THREAD

**Issue by djlauk** [runem/lit-analyzer#108]
While reviewing some code I looked at vscode's "problems" view and noticed, that the messages the lit-plugin extension adds do not have an indicator where they come from. In this screenshot you can see, how other plugins add such information:

![image](https://user-images.githubusercontent.com/3351287/85539550-41efed00-b616-11ea-929f-9057dbc1314c.png)

(Notice the decorators "eslint(...)", "ts-styled-plugin(...)", and "ts(...)".)

In this particular case it would have helped me to quicker identify, which vscode plugin my coworker is missing.

**Comment by runem** [comment]
Thanks for reporting this :-)

In order to align with eslint, diagnostics will end up with this naming convention: `lit-plugin(no-expressionless-property-binding)`.

**Comment by runem** [comment]
It will look like this in the future:

<img width="748" alt="Screenshot 2020-07-06 at 14 32 20" src="https://user-images.githubusercontent.com/5372940/86593495-9f305a80-bf95-11ea-94db-b72a960b838c.png">

**Comment by djlauk** [comment]
Looks great. Thank you so much!
