### ISSUE TITLE
[ts-lit-plugin] compatibility with webstorm

### ISSUE THREAD

**Issue by FelixSchuSi** [runem/lit-analyzer#124]
Yesterday I found out that v. 1.2.0 of `ts-lit-plugin` broke compatibility with webstorm.
Which is a bummer since most of my co-workers use webstorm.
While everything else works as expected, the codefixes dont show up.

I have traced this down to the patch of `"getSupportedCodeFixes"` [here](https://github.com/runem/lit-analyzer/blob/master/packages/ts-lit-plugin/src/decorate-language-service.ts#L31).
As pointed out by @runem [here](https://github.com/runem/lit-analyzer/issues/113#issuecomment-655098475), we need to tell the language service which rules can generate codefixes by patching the `"getSupportedCodeFixes"` on the tsmodule. While calling `"getSupportedCodeFixes"` on the tsModule works, the patch itself doesnt have the desired effect in webstorm.

Before we used unique codes for the rules in `lit-analyzer` (ranging from 1 to 23), diagnostics of every rule were reported with the code 2322. Using the code 2322 means that we do not have to patch the `"getSupportedCodeFixes"` function, since 2322 is one of many [typescript internal error codes](https://github.com/microsoft/TypeScript/blob/master/src/compiler/diagnosticMessages.json) that are allowed to create codefixes.

I have played around with this quite a bit and I couldnt get the patch to work in webstorm. The only workaround I could find was using rules that collide with typescripts internal error codes so that the patch becomes obsolete. I will file a PR with this workaround soon.

I really hope we can keep compatibility with webstorm so that my co-workers and every other webstorm user can continue to use this plugin.

**Comment by runem** [comment]
Thanks for reporting and fixing this issue :tada:
