### ISSUE TITLE
Highlighting the closing tag within html

### ISSUE THREAD

**Issue by tvvignesh** [runem/lit-analyzer#140]
Hi. In VSCode or any editor for that matter, selecting the start of the tag will automatically highlight the close tag like this:

<img width="182" alt="Capture" src="https://user-images.githubusercontent.com/1165845/93668675-a7376b00-faab-11ea-84e0-f49e76a1f08d.PNG">

However, I am not able to do that in the html I write with Lit's render method. Any ways matching tag highighting can be provided? Thanks.

**Comment by abdonrd** [comment]
Duplicated of https://github.com/runem/lit-analyzer/issues/33
