### ISSUE TITLE
Complex attribute converter still triggers incompatible-type warning

### ISSUE THREAD

**Issue by e111077** [runem/lit-analyzer#260]
When setting a complex attribute converter on a property to accept complex data types e.g.:

```ts
@property({converter: {toAttribute: ..., fromAttribute: ...}, reflect: true})
date = new Date();
```

lit analyzer gives the following issue:

```
The built in converter doesn't handle the property type 'Date'. Please add '{attribute: false}' on @property decorator for 'date'lit-plugin(no-incompatible-property-type)(2303)
```

**Comment by bicknellr** [comment]
Could you expand on the example? I've been having trouble reproducing this.

**Comment by e111077** [comment]
I cannot reproduce anymore. Must've been fixed somewhere along the line!
