### ISSUE TITLE
Support for Typescript v4.8.2

### ISSUE THREAD

**Issue by Ben-Barron** [runem/lit-analyzer#272]
I've just upgraded my version of Typescript in my project to v4.8.2 and I've now lost support for recognising custom elements in `html` blocks. It's now showing `unknown-tag` in Visual Studio Code for all my custom elements.

If I downgrade Typescript to v4.7.4, it works fine.

VS code v1.70.2
ts-lit-plugin v1.2.1
vscode-lit-pluin v1.2.4

**Comment by SimonAlling** [comment]
More info in #278.

**Comment by rictic** [comment]
This is fixed at `@next` and with the latest version of the VSCode plugin
