### ISSUE TITLE
With TypeScript 4.8 we seem to only see info from .d.ts files

### ISSUE THREAD

**Issue by rictic** [runem/lit-analyzer#278]
Consider this repro: https://github.com/HalfdanJ/lit-element-starter-ts (recommend opening a github codespace to get a stand alone fresh install of the VSCode plugin, with only local configuration)

With a same-project import of `some-element`, we still get an unknown tag warning unless it's added to the HTMLElementTagNameMap, and even if it is we get an unknown attribute warning unless we add an `@attr` jsdoc tag to SomeElement. It's as though the analyzer can't see the `@property` or `@customElement` decorators

**Comment by rictic** [comment]
@bicknellr

**Comment by bicknellr** [comment]
I just now put two and two together and realized this is the same as the internal bug we were handed recently. Recap: [TypeScript 4.8 changes the location of decorators in the AST](https://devblogs.microsoft.com/typescript/announcing-typescript-4-8/#decorators-are-placed-on-modifiers-on-typescripts-syntax-trees) and [web-component-analyzer's `discoverDefinitions`](https://github.com/runem/web-component-analyzer/blob/be1dd3cbcfe4f8a5a37b6cccc9232a1588303372/src/analyze/flavors/lit-element/discover-definitions.ts#L13) for Lit specifically expects to find decorators [in the old position](https://github.com/runem/web-component-analyzer/blob/be1dd3cbcfe4f8a5a37b6cccc9232a1588303372/src/analyze/flavors/lit-element/discover-definitions.ts#L19). I'm working on adding support for TypeScript 4.8 in <https://github.com/runem/web-component-analyzer/pull/249>, which includes updates to look for decorators in the new location.

**Comment by pmcelhaney** [comment]
That PR has been merged but there hasn't been a release since then. Pretty pretty please can you cut a new release? 😄

**Comment by SimonAlling** [comment]
A new version of this package based on a not-yet-released version of [`web-component-analyzer`](https://github.com/runem/web-component-analyzer) would indeed be highly appreciated. Until that happens, many consumers – especially those who use `"no-unknown-tag-name": "error"` etc – cannot upgrade to TypeScript 4.8 and beyond. I don't know how releases are managed or by whom … @runem, @rictic, @bicknellr?

**Comment by rictic** [comment]
This should be fixed now, install the `@next` version
