### ISSUE TITLE
Latest VS Code update breaks editor IntelliSense

### ISSUE THREAD

**Issue by JulianCataldo** [runem/lit-analyzer#299]
Hello there,
thanks a lot for making this plugin, it really helped me to dive into the Lit world at the beginning.

I don't have much experience, nor actuals clues on how to exactly report my problem but,
I noticed on two different computers that some recent VS Code update broke `ts-lit-plugin` (via VS Code extension) IntelliSense feature.

I fiddled a bit with the log, and it seems the plugin still got activity under the hood.

Just wanna report this, in case of anyone else is affected. I will report further observations.

**Comment by sakralbar0192** [comment]
Hello! Thanks a lot for lit. I really like to create my web applications with it.the lit plugin helped me a lot in my work. But it's not working right now. Please fix it.

**Comment by JulianCataldo** [comment]
It's working again 😋
I guess, maybe the VS Code or TypeScript teams did something?

Anyway, thanks again for your work 🙌

**Comment by fdesforges** [comment]
The plugin don't work on typescript 5, so you have to switch back to typescript 4.x on you file using the version selector : https://code.visualstudio.com/assets/docs/nodejs/working-with-javascript/partial-mode-status-item.png

**Comment by nevermindthelabel** [comment]
> The plugin don't work on typescript 5, so you have to switch back to typescript 4.x on you file using the version selector : https://code.visualstudio.com/assets/docs/nodejs/working-with-javascript/partial-mode-status-item.png

Thank you, this was a lifesaver. Totally different issue but the TS version was what broke it.

**Comment by kaseyhinton** [comment]
Any idea when this plugin will get updated so we can use the latest typescript version? For lit-plugin it is breaking intellisense as well some of the validation rules.

Thanks for the workaround!

**Comment by RoenLie** [comment]
+1 for hoping this will be looked at.

**Comment by Galbrain** [comment]
This is still an issue. Does anyone have information if this problem is even looked at?

**Comment by rictic** [comment]
VSCode plugin v1.3.0 has been released

**Comment by JulianCataldo** [comment]
A bit late, but just to confirm that everything went smooth DX-wise with Vite Lit TS template and VS Code lit-plugin, out-of-the-box. Just tested recently.
Huge thanks for those who made this possible. I cannot understate how this makes working with Lit and Web Components even more awesome!
