### ISSUE TITLE
doesn't work anymore

### ISSUE THREAD

**Issue by alimrb** [runem/lit-analyzer#301]
All the features stopped after last vs-code update:

Version: 1.77.0 (user setup)
Date: 2023-03-29T10:02:16.981Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
Sandboxed: No

**Comment by alimrb** [comment]
Name: lit-plugin
Id: runem.lit-plugin
Description: Syntax highlighting, type checking and code completion for lit-html
Version: 1.2.4
Publisher: Rune Mehlsen
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=runem.lit-plugin

**Comment by dlin-me** [comment]
As one of the issues reported 4 months ago indicated, this plugin does not work with Typescript v5.  Recent vscode update sets typescript v5 by default. You can set the version to v4.xx and it will work again.

**Comment by alimrb** [comment]
> As one of the issues reported 4 months ago indicated, this plugin does not work with Typescript v5. Recent vscode update sets typescript v5 by default. You can set the version to v4.xx and it will work again.

Yes, problem solved. Thanks.
