### ISSUE TITLE
lit-analyzer is not compatible with latest TypeScript

### ISSUE THREAD

**Issue by bicknellr** [runem/lit-analyzer#302]
lit-analyzer needs to be updated to work with and test on the latest version of TypeScript. Here are a few issues already that either point this out directly or at least seem related:

- https://github.com/runem/lit-analyzer/issues/272
- https://github.com/runem/lit-analyzer/issues/287
- https://github.com/runem/lit-analyzer/issues/290
- https://github.com/runem/lit-analyzer/issues/299

I haven't scanned through to find all related issues so there are likely others.

**Comment by gautelo** [comment]
Bumping to say, I'm also hopeful for a fix to this.

**Comment by gautelo** [comment]
I'm guessing this is related to #299

**Comment by rictic** [comment]
This should be fixed now, install the `@next` tag
