### ISSUE TITLE
[vscode-lit-plugin] Typescript 5.1 Missing import warning for <my-element> doesn't work

### ISSUE THREAD

**Issue by herberthobregon** [runem/lit-analyzer#313]
@rictic Missing import for <element> still doesn't work with latest typescript version

**Comment by Galbrain** [comment]
Me and my colleagues the same issue still.

**Comment by herberthobregon** [comment]
Currently I use 4.7.4. I'm waiting for this problem to be solved

**Comment by benjamind** [comment]
This is also causing problem for us on some rather large projects at Adobe....Is this plugin pretty much abandoned at this point for the work going on in the main lit project or is there hope for a fix here?

**Comment by benjamind** [comment]
Reproduction here: https://github.com/benjamind/vscode-lit-plugin-313-repro

Seems to be related to `tsconfig.json` `module` setting being present.
