### ISSUE TITLE
[vscode-lit-plugin] Auto close tag does not work anymore in lit-template

### ISSUE THREAD

**Issue by cWenyu** [runem/lit-analyzer#325]
Hi, 

I recently found the **lit-plugin v1.3.0** does not auto close tag, I recorded two small videos to show the difference between vs code 1.76.2 and 1.82.2. However, vscode-lit-plugin does not work as expected in version 1.76.2 either, only the first element is auto-closed and the second one does not. 
<br/>Please let me know if you need more information. 
  
**Visual Studio version: 1.82.2**

https://github.com/runem/lit-analyzer/assets/45832472/bbb907c9-c3b6-4e01-84ee-2014e069c3d0

**Visual Studio version: 1.76.2**

https://github.com/runem/lit-analyzer/assets/45832472/e74b1590-eff0-4f85-b445-bbd15fc93976

Best regards

**Comment by cWenyu** [comment]
update typescript to v5.2.2 would solve the issue.

**Comment by damooo** [comment]
It still doesn't work after typescript update.

**Comment by cWenyu** [comment]
Have you checked on different versions of vscode?
