### ISSUE TITLE
The new lit-plugin 1.4.0 has broken all my Lit projects.

### ISSUE THREAD

**Issue by herberthobregon** [runem/lit-analyzer#328]
They have now removed support for the only version of typescript that worked. typescript 4.7.4 does not work and typescript 5.2 does not work well either. Now it's like coding in plain text

I don't understand why such a simple example couldn't be tested before launching it into production.
![image](https://github.com/runem/lit-analyzer/assets/6503845/66ae84f2-e146-4c9e-a20b-eb53cd64dc5f)

I have prepared a repository so you can try it. It is the simplest.

https://github.com/herberthobregon/lit-test

**Comment by herberthobregon** [comment]
@rictic @justinfagnani Could you check this?

**Comment by rictic** [comment]
There was a build script issue. Published v2.0.1 which should fix, apologies for the breakage!
