### ISSUE TITLE
missing import error when import isn't missing

### ISSUE THREAD

**Issue by shaiallseated** [runem/lit-analyzer#330]
![image](https://github.com/runem/lit-analyzer/assets/127416369/a165b445-2013-4b51-a2ad-08853f70e3c3)

**Comment by NKoroloff** [comment]
I have problem too

**Comment by kenzoi** [comment]
I'm having the same warning.

**Comment by AndrewJakubowicz** [comment]
Thank you for filing the issue. This should be fixed once https://github.com/runem/lit-analyzer/pull/338 is released.

**Comment by shaiallseated** [comment]
Thanks, seems to work, I love you 🍝
