### ISSUE TITLE
HTML Attributes can use either ' or " for quoting values

### ISSUE THREAD

**Issue by rictic** [runem/lit-analyzer#36]
These are equivalent:

```typescript
html`
  <a href="foo.html" target="_blank"></a>

  <a href='foo.html' target='_blank'></a>
`;
```

However, the analyzer emits an error for the second one, because it considers the type of the value to be `'\'_blank\''` instead of just `'_blank'`.

**Comment by rictic** [comment]
This error also has a pretty straightforward workaround of just using double quotes, but it would be nice to fix.

**Comment by runem** [comment]
Great catch! This has now been fixed and will come out with the next release :+1:
