### ISSUE TITLE
Running type checks from command line / as tsc plugin

### ISSUE THREAD

**Issue by justinfagnani** [runem/lit-analyzer#41]
We'd really like to run the template type checks as part of the tsc compilation. Not all of the same services are available as easily in that environment, and for now there's no way to specify plugins as part of the tsc configuration, but figuring out some way to have the same errors would be extremely valuable.

**Comment by runem** [comment]
It's now possible to analyze templates from the command line using the [`lit-analyzer`](https://github.com/runem/lit-analyzer/tree/master/packages/lit-analyzer) CLI like this:

```console
npx lit-analyzer src --strict
```
