### ISSUE TITLE
Support css ::part & :state

### ISSUE THREAD

**Issue by mantou132** [runem/lit-analyzer#78]
https://github.com/runem/lit-analyzer/tree/master/packages/vscode-lit-plugin#-documenting-slots-events-attributes-and-properties

https://drafts.csswg.org/css-shadow-parts/
https://github.com/w3c/webcomponents/blob/gh-pages/proposals/custom-states-and-state-pseudo-class.md

**Comment by mantou132** [comment]
![decorator](https://user-images.githubusercontent.com/3841872/72625764-5c95aa00-3984-11ea-94c1-9bebdb856b30.png)

Hope that lit-analyzer can generate documents based on decorators, and lit-plugin can auto-complete based on decorators

**Comment by runem** [comment]
### ::part & :state

`::part` is currently autocompleted, but `:state` is not. I think it's a great idea to autocomplete `:state` as well :+1: 

### Support for custom decorators
I actually already responded your request in this issue: https://github.com/runem/lit-analyzer/issues/71#issuecomment-567435280. Please follow up in that issue if you have any questions :-)

**Comment by mantou132** [comment]
Thank you.
When I have extra time, I will dig deeper
