### ISSUE TITLE
Using enums for properties or attributes

### ISSUE THREAD

**Issue by Christian24** [runem/lit-analyzer#80]
Hello,

I just started testing lit-analyzer and I noticed something with the way we use enums: Think about the following property: 

````typescript
@property({ type: String })
public type: AlertType = AlertType.SUCCESS;
````
`AlertType` itself looks like this: 
````typescript
export enum AlertType {
  SUCCESS = 'SUCCESS',
  DANGER = 'DANGER',
  WARNING = 'WARNING',
  INFO = 'INFO',
}
````
Now it is very easy to use this since I can just go:
````typescript
<my-component type="${AlertType.SUCCESS}"></mycomponent>
````
This works great since the enum at runtime just gets transpiled to a String and I do get code completion in my IDE. However, lit-analyzer does not recognize this and fails with `Type 'string' is not assignable to 'AlertType'`.

**Comment by dgoogles** [comment]
Could you try with the property dot syntax instead:

.type="${AlertType.SUCCESS}"

**Comment by Christian24** [comment]
I tried that. It leads exactly to the same error.

**Comment by herberthobregon** [comment]
Is a `typescript` problem

Update your typescript version

## Test:
`typescript@3.8.0-dev.20200107`

![s](https://fotos.subefotos.com/9cf4a75a5311a7f68710142f89701909o.png)

**Comment by Christian24** [comment]
@herberthobregon is right, it was the Typescript version. 3.8 works great.
