### ISSUE TITLE
Unwanted warnings for @property() with no args

### ISSUE THREAD

**Issue by realh** [runem/lit-analyzer#84]
lit-plugin generates warnings about the lack of a `type` wherever I use `@property()` with no arguments. I've tried setting `no-expressionless-property-binding` and `no-unknown-property-converter` to `off`, but neither disables the warnings. I've seen a reference to a `no-unknown-lit-element-property-type` in another issue, but there doesn't seem to be a corresponding entry in the settings GUI, and adding it manually to the JSON doesn't disable the warnings either.

**Comment by runem** [comment]
Hi, thanks for opening this issue! I'm sorry that you are experiencing problems.

Until now unfortunately it hasn't been possible to control the config, but https://github.com/runem/lit-analyzer/pull/112 fixes this. I'll close this issue when the PR has been merged into master and published.

Just to clarify things:
- `no-expressionless-property-binding` is for catching: `<my-element .myProperty="hello"></my-element>`
- `no-unknown-lit-element-property-type` and `no-unknown-property-converter` has been merged into one rule called `no-incompatible-property-type`. This is the one you should be adjusting when `1.2.0` is released :-)
