### ISSUE TITLE
Feature request: support types in @fires jsdoc

### ISSUE THREAD

**Issue by e111077** [runem/lit-analyzer#85]
Currently the biggest issue with TS and DOM is event type checking. TS has support for `HTMLElementEventMap` where you can associate an event name with an event type. e.g.

```ts
declare global {
  interface HTMLElementEventMap {
    'my-custom-event': CustomEvent<{ foo: string }>;
  }
}
```

but that unfortunately applies to every element. I believe that adding support for types in the `@fires` jsdoc should provide element-specific checking with lit-analyzer and can help prevent issues, if not through TS compilation, then via CI checking. Here is an example:

```ts
// my-element.ts
interface MyCustomEventDetail {foo: string};
/**
 * @fires my-custom-event {MyEventDetail}
 * @fires my-event
 */
export class MyEvent extends LitElement {
...
  fireCustomEvent() {
    const ce = new CustomEvent<MyCustomEventDetail>(
        'my-custom-event',
        {detail: { foo: 'bar'}, composed: true, bubbles: true}
    );
    this.dispatchEvent(ce);
  }

  fireEvent() {
    const evt = new Event('my-event', {bubbles: true, composed: true});
    this.dispatchEvent(evt);
  }
}
```

Then consuming the event:

```ts
...
html`
  <my-element
      @my-event=${this.onMyEvent}
      <!-- Type checking happens here -->
      @my-custom-event=${this.onMyCustomEvent}>
  </my-element>`
...

onMyEvent(evt: Event) { ... }
onMyCustomEvent(evt: CustomEvent<MyCustomEventDetail>) {
  console.log(evt.detail instanceof string); // true
  ...
}
```

related #73

**Comment by runem** [comment]
The newest version of WCA / LitAnalyzer now correctly analyses even types. Therefore I'll close this issue now :+1:

**Comment by e111077** [comment]
you're on `@fire`! 🔥
