### ISSUE TITLE
The warnings should not fail in the CLI

### ISSUE THREAD

**Issue by abdonrd** [runem/lit-analyzer#94]
I expect the warnings should not fail in the CLI, just the errors.

<img width="799" alt="Screenshot 2020-04-28 at 20 03 09" src="https://user-images.githubusercontent.com/1007051/80521482-62d7f100-898b-11ea-9b08-8a849a6bbf97.png">

```
> lit-analyzer "src/{components,pages}/**/*.ts" --strict

Analyzing 4 files...

./src/components/app-shell.ts

    Unknown tag <pwa-install-button>.
    67:  <pwa-install-button>
    no-unknown-tag-name

    Unknown tag <pwa-update-available>.
    71:  <pwa-update-available>
    no-unknown-tag-name

  ✖ 2 problems in 1 file (0 errors, 2 warnings)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pwa-starter@0.1.0 lit:check-types: `lit-analyzer "src/{components,pages}/**/*.ts" --strict`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pwa-starter@0.1.0 lit:check-types script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

An example with ESLint:

<img width="617" alt="Screenshot 2020-04-28 at 20 06 32" src="https://user-images.githubusercontent.com/1007051/80521811-ee518200-898b-11ea-91b9-d4809ab0a780.png">

**Comment by 43081j** [comment]
i think you can specify `--maxWarnings -1` but it probably should be the default behaviour

**Comment by abdonrd** [comment]
@43081j thanks for the answer! But same behaviour with this:

<img width="839" alt="Screenshot 2020-04-29 at 10 28 45" src="https://user-images.githubusercontent.com/1007051/80575703-475cfc80-8a04-11ea-888a-187405d51fe1.png">

Also [in the README docs](https://github.com/runem/lit-analyzer/tree/master/packages/lit-analyzer#available-arguments), the default value is `0`:

**Comment by abdonrd** [comment]
I find the issue! Seems to save the `maxWarnings` as `true` instead as `-1`:

<img width="529" alt="Screenshot 2020-04-29 at 11 16 49" src="https://user-images.githubusercontent.com/1007051/80579957-1cc27200-8a0b-11ea-851a-cbf23bbe7d0d.png">

**Comment by abdonrd** [comment]
Ready at #96! 🎉

**Comment by runem** [comment]
Hi, thanks for your suggestion!

I modelled the configuration [after ESLint](https://eslint.org/docs/user-guide/command-line-interface#handling-warnings). Reading the description of `--max-warnings` it seems like the change you propose @abdonrd aligns with what ESLint does, so I will go ahead and merge :+1: 

Here is the description of `--max-warnings` from ESLint if you are interested :-) 

```
This option allows you to specify a warning threshold, 
which can be used to force ESLint to exit with an error status 
if there are too many warning-level rule violations in your project.

Normally, if ESLint runs and finds no errors (only warnings), 
it will exit with a success exit status. 
However, if --max-warnings is specified and the total warning count 
is greater than the specified threshold, ESLint will exit with an error status. 
Specifying a threshold of -1 or omitting this option will prevent this behavior.
```
